---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${BUCKET}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: kubernetes-local
  target:
    name: ${BUCKET}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: '{{ .info | fromJson | dig "spec" "secretS3" "accessKeyID" "" }}'
        AWS_SECRET_ACCESS_KEY: '{{ .info | fromJson | dig "spec" "secretS3" "accessSecretKey" "" }}'
        BUCKET_NAME: '{{ .info | fromJson | dig "spec" "bucketName" "" }}'
        BUCKET_ENDPOINT: '{{ .info | fromJson | dig "spec" "secretS3" "endpoint" "" }}'
        BUCKET_HOST: '{{ .info | fromJson | dig "spec" "secretS3" "endpoint" "" | trimPrefix "https://" | trimPrefix "http://" }}'
        BUCKET_REGION: '{{ .info | fromJson | dig "spec" "secretS3" "region" "" }}'
        RESTIC_REPOSITORY: '{{ printf "s3:%s/%s/restic" (.info | fromJson | dig "spec" "secretS3" "endpoint" "") (.info | fromJson | dig "spec" "bucketName" "") }}'
  data:
    - secretKey: info
      remoteRef:
        key: ${BUCKET}-raw
        property: BucketInfo
