apiVersion: v1
kind: Secret
metadata:
  name: old-restic
stringData:
  RESTIC_REPOSITORY_BASE: ENC[AES256_GCM,data:KeAYdaCItTDSo+pXepzO01VKpZOhIb7R+dK5qIOwFaCFWStujHBFvbxq5pJ5Sbc19Js9XotxQl+kjrZY,iv:wpZgKFrzpqysRLJoufxkspytUIe2uuKs2TU89btzwTY=,tag:uPiSTdbWWm+4kXMmUFKrmQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ebYNg8hcoZcj5c6GnSXep1kJpS9wirO1,iv:xQI2OESuwT62lbKK5i594ef6e7NyAsKnEWN2rlZHf/M=,tag:YwMIM/HmItyRijjFLz1kgw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h/jIaU5ZUfb2X33mlyG0nUYxwY1EgTUhYg==,iv:7UPcu6/Wu3VK422fuO+PTYsYTnkB0ZXK01wj0X6s4aI=,tag:zQH3sLbd+tVO1ht9dtSP1Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JG91C+fCWRkZwQZR6XZV+18DyGQFYushuewd53t8ZA==,iv:AQROoLFiugJLJ7lfdwgqxB2wSFQBTXHXl5Ld0wXPBQY=,tag:5kEgdp1/CPIc1TNjGAZURA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNnRSamtTRlJsY3lYV2d5
        S2lEcTQyYmM4ZHRTUk5BZ2JvSnlZeFJtZ2kwCms5RzlWWXZUSHIyakdvR05wc0tD
        Qmswbmo1V0F0UTE2YlBQelZPbFM3U1kKLS0tIHROd3NLalRyOGl5OFZGbUFpZXov
        bEpQOWJ0dGN4c3hSWi9PKzlhaGgxbGsKSE5OiFawwcdo3KraxfCO9z6CXZkAComA
        /CvF2jwyMafp/k0BBUkYYLT5blo7lq1aUis+KQc483J0Wn2p0gDzNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T12:14:03Z"
  mac: ENC[AES256_GCM,data:AlF3C9BDitw4AVInI4i4z38r1jNgLpojzfX7vG1TiDW79iFd+cWptgbim0NA7AVOT2w8C9HK6pZbeIYZhD2hTxfdUBobf4xNTiDB0X6VxEZXeJzQVhF1a5k1M/Cx+CAmSl9C4jrjok7jSgfDja6slb+c6UMm6oM/m5tAquGO1Oo=,iv:gtz/+/+P6go+bKWOnexth3OtM4ylKk4It9lyhvx1uCM=,tag:N5AfwtdFmFVsKJpkonOsnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
