apiVersion: v1
data:
  ADMIN_PASSWORD: ENC[AES256_GCM,data:biNVc5boxmiBX60n40W6Ge/M5nX+oZkfpoQlNqebtp0jT7GBy8EZvIZSa3Q=,iv:BPj3XscS0M1LeWT7lqJsQzhkP+7clz5DApNOTl+HYTM=,tag:NPTy/l9Uwzx6nE4be8J27w==,type:str]
  OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:rRIGPNQIBXTybc+qcpTT7qSNtE2WWnaTRy9IfhKBr5ZRu+n2MCbIMGFyD1YLLszO2Qw1q41Fl6M=,iv:icn32oEPfKjqLNePbvP2mdraD//iayiAGxq36PMH9Ys=,tag:p5RYEBA8M/L+0M4QQkXvMg==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:AxU1jCT/Ycv3SshOoiSrYa3R6SkkaeygDdgtuvClfns2fuzBKvQcnUTEk60qtQ1tzwomqGsENv1a5zb431vRfD5EktHoDKIucgHdKvaxgJMYC2CmFnlzxiOIzktgheOIZtpsMQVhuUWGZMPtScexVo1aNJrHC8IQpz+TMkqussBrhcHn9jqLLXvPOZYoVnIjwxRj+IS9pSb9f5dMhbCho1jKegSWk3/bp1kqbw==,iv:VjWGaklTrpK2viBp+LoqNtiGGKHTSYC3tefXzc1ik+U=,tag:R2lCyF0xY1FOMCa5kDQBXQ==,type:str]
kind: Secret
metadata:
  name: miniflux-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyamFSZ2Z3bksxR003M2wz
        NXlheGpyZFBEQkM4TGtWUjE2UnprZ1ROQ0d3CjBQOTh3bnUvNDZNMUpYVXd4eWJ0
        UnNSSjhjbXR5TU5xeUgrY1JVazQrTWcKLS0tIC9BWEFicWxqbkNOUmV5bTMzMnNp
        UFlWZktId1BpR0thL2xaUUY3TlBKNXMKfZqVT+B0eGZRwBqPTDJWa2d5DFkbhxHF
        SoLtr0lAs2FGtcRmUkgbkot2IB3TDkBD/4TDpRqa/DXweS0CouNh0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T17:51:01Z"
  mac: ENC[AES256_GCM,data:PBxXh02oN7xDaMNWWa2QFJ5SjtQ4YxnOMMAk0UayaClBJBdrUhEBac7N5yBtwrL/wIgn1sf8NZXC33NLfTUMw67AcDty/rcapDLXAccQY9uV2RRlYTzKD08w9GzWO1xRG/nzyiKpuQcIA993s34G25HdotaW7uRnsXbG7fwYK60=,iv:tjy5EDfIUcM6RmUCSHYXVr00OxJtySBssBWaFG4o9KI=,tag:6pJ7wjKOzm/7lgINBLEqdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
