---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda-add-ons-http
spec:
  chartRef:
    kind: OCIRepository
    name: keda-add-ons-http
  interval: 1h
  values:
    operator:
      resources: &resources
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 128Mi
    scaler:
      resources: *resources
    interceptor:
      resources: *resources
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: keda-add-ons-http-.*
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: infra
