apiVersion: v1
kind: Secret
metadata:
  name: kopia
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:VWJ3IR9aeyN19OVhI33A4WBiGFlxFnPQo8b8Rwrq4Pg=,iv:mTDG6i6WIiYGZl72GpaK3mNEKzQnCiqvUqoWn2THRUw=,tag:UmnxM8ymgBH7xED82eTG7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SndsOGRTd1RNdUYyOVYz
        azNxSW5CNTRrK3hKMHFyR2Q1Q1g1ODVoS2drCnhJZm5PajBZa3VmdTJoc0puYjFo
        K3d0UHEyajRWazhqQzEzOGVYbWxBRmcKLS0tIE9BQXdxZDFzVmZZOWVLRWhocEda
        S1A1R3ptWVQ0K1FLZXQ3aG9WLzNmYUUKEZUJDMusT45AMZ8KG0ywIAuk2Vm3EcH5
        x2hDf8ngPrQg6Br3jSf1/I76zxH2/W5GCdKAtIVIxtRphiPm4vKyKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T19:03:42Z"
  mac: ENC[AES256_GCM,data:YwSgUCtigwVv9ZiieqloCF3SkribjmnV7DBuMhEvRmoMeAXz4jTptbdWQdpOHy+zdMuprCslLZ0sj6v5CzRGpa3sa/ZuXkBG8sw4aSjvCK1lwdynXwXYe/FqgU9PvMdTgoZ6SOd85exkLSY4CUBAW0NqFNv6iicuhpzOOwL2GBE=,iv:1ShUTQ6QWoSs2pbjVwk9/nXyX0dpj1RY7ikyHBkVXuM=,tag:kQ5Z07Dw78J+dAasSTV+ew==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
