apiVersion: v1
kind: Secret
metadata:
  name: restic
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:VWJ3IR9aeyN19OVhI33A4WBiGFlxFnPQo8b8Rwrq4Pg=,iv:mTDG6i6WIiYGZl72GpaK3mNEKzQnCiqvUqoWn2THRUw=,tag:UmnxM8ymgBH7xED82eTG7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SndsOGRTd1RNdUYyOVYz
        azNxSW5CNTRrK3hKMHFyR2Q1Q1g1ODVoS2drCnhJZm5PajBZa3VmdTJoc0puYjFo
        K3d0UHEyajRWazhqQzEzOGVYbWxBRmcKLS0tIE9BQXdxZDFzVmZZOWVLRWhocEda
        S1A1R3ptWVQ0K1FLZXQ3aG9WLzNmYUUKEZUJDMusT45AMZ8KG0ywIAuk2Vm3EcH5
        x2hDf8ngPrQg6Br3jSf1/I76zxH2/W5GCdKAtIVIxtRphiPm4vKyKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T10:25:50Z"
  mac: ENC[AES256_GCM,data:od5G/DkFZtgXyVY5fanFUWdQSAkGYNRV4WShQ30WR4HgEkoJ2rJhVTGXupUJhUclZVGMDPipJeSefygPI9u343k4gPXwGPAN6Ml23RyXHhxefiobjIif1CeU31m3qOI4798wIE9O/dIs3NgJGhf9p4J8xwTLyBY7qaoGT6zeHLc=,iv:u6PMOLt35Hzps0hKOny9GCtGt7iOqT4AttdJ+8eOJDQ=,tag:yYJ2QFzqiki6SQEQWEJWaA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
