apiVersion: v1
kind: Secret
metadata:
  name: b2-credentials
stringData:
  applicationKeyId: ENC[AES256_GCM,data:qfTkeZOTAs1gx3fi1V+dz6mnHx7vkyTWbA==,iv:aJCjGZQuDHGcPT1nQrWAGscoe+3OP4YsOTa7Ie0k4tQ=,tag:7JTAeVPBgLXklaFLf8isxQ==,type:str]
  applicationKey: ENC[AES256_GCM,data:6cFzUwk5gspVOM64RHxC6LCwIfpHw9ztbSG6yTA0rg==,iv:YjU/Db+Wm4oa3DO0QrDMF/W8olgKjo8u+gpuWeGfGoE=,tag:evOdXjAbnFWlaI31ZtoVOQ==,type:str]
sops:
  age:
    - recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdXd3U3lkQjl3V05HR1dS
        RXp5eVVRVWR4eUtsMHU1N0grYzdYN3NoaFZNCjhmSllpOE92OHJsSmJPOGNqeElI
        N2NpUnBNSnNiR1Q5TWRhQkg5YkxwOVkKLS0tIENlTWNFUU5sVHQ2ZFpodUpjSHJi
        UGNXSk0rbEpabk95RlBmWFNJdnNYdVUK+pmbeZFUXKStgDTGwqVDTDotQdjivd4d
        WIvzztHk3fCjFGuLgGNUFv9KYIoKOv3TPcN+HS76G0mwCfBMelF+Yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T14:35:36Z"
  mac: ENC[AES256_GCM,data:lNxSbAKuSw6zFG6ifkjO0QCKJI6FDHU/YZhH0bkCfXVKK5ho6jxea92gVOvd0BQmkslGrrpCtvDkBuy4Kd72dzNJoFFZdXyOiK2BUArBIWFE00yQNFkMvKIRg10lTdiccT26cB4HHbW3n9dB75fJfHNcdP4MFbara0TuSaTjHHk=,iv:M+UmqcHwARZSSLgi+3VBENHAouJ4XMhJSGqMLNGVbiU=,tag:knQWwTO66MsBhwEaXik0hQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
