---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
  interval: 1h
  values:
    vmsingle:
      spec:
        retentionPeriod: "2y"
        storage:
          storageClassName: ssd-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi

    vmagent:
      spec:
        resources:
          requests:
            cpu: 50m
            memory: 192Mi
          limits:
            memory: 384Mi

    vmalert:
      spec:
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 128Mi

    alertmanager:
      spec:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi

    victoria-metrics-operator:
      resources:
        requests:
          cpu: 10m
          memory: 96Mi
        limits:
          memory: 192Mi

    kube-state-metrics:
      resources:
        requests:
          cpu: 25m
          memory: 96Mi
        limits:
          memory: 192Mi

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi

    grafana:
      enabled: false
      forceDeployDatasource: true

    kubeEtcd:
      endpoints:
        - 10.0.10.12
        - 10.0.10.13
        - 10.0.10.14
      service:
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            - port: http-metrics
              scheme: http

    defaultDashboards:
      grafanaOperator:
        enabled: true
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true

    defaultDatasources:
      grafanaOperator:
        enabled: true
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true
