---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
spec:
  interval: 15m
  ref:
    tag: 0.90.1
    digest: sha256:34e7f6841918de0a01b04489e445cce915c76e9870401a98779864bb15821689
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
