---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
spec:
  interval: 15m
  ref:
    tag: 0.91.1
    digest: sha256:27f99fd54f1af21c97ca5694465b2e30be769c7d06723b4accf537abd812160c
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
