---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
spec:
  interval: 15m
  ref:
    tag: 0.94.0
    digest: sha256:9db6261ee258901cddca27eb96f8ef37435d7f6184dc786eb30f73eed8254cfc
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
