---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shelly-exporter
spec:
  interval: 1h
  path: ./kubernetes/apps/monitoring/shelly-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: prometheus-operator-crds
