apiVersion: v1
kind: Secret
metadata:
  name: actual-oidc
stringData:
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:0QvxRORzLTFEFbHWm8rHSRWgJ+msOMWtUbd7zcg5BgY66fP977fPEA==,iv:oE2GIiOnPud0QJilLxkp1WZDHgDRwLTLpDO1szRWDqU=,tag:86qUD8XnRJfizt30LKC+Ng==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:gWDvZw7a2sohbVRDFLddEFJC3+bwr94tJ/eprU+/7f37COldlQvRl6utGcgx4M0EBrJvsdCSRY5JlrVstXYDi3scyTTyAV6AEl/ucFHFjiAoEr965Qf6H+y2KL+EVktXOJzZ+JmSkzfyQxhxd2kOwzIQF6U5iyRp1pMeOINOh6s=,iv:WoaduwIiotBnU3q84T4KEJEkXRrJjtNJXHg5gJC8VWo=,tag:UKK3FXi6upr70WP7J0nVUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOTRYWUlwNVQ3TWtzcno5
        RWdDbTFhNy81c1JaVTl5ZFlYOUs0aVRoUHlnCkJRcm5UdFkyYzNzNTJ0MklDRm5i
        SjJFR05mRXpzZ3NMRXRIVGl1Ry82UVkKLS0tIHowZWZxV05nRUZLSm1EOFBLVEhB
        WG5PYkJhaHYxV1BVUEVtM21URXE0WGMKUGYcXfkCxsV9QQzLnOvm+oRwoQ17g1C8
        CZ59AwIjTs2cTOWCRkfJW3zxg9AdRR6k3op2R0E1DGBIMignGpzZnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T07:15:19Z"
  mac: ENC[AES256_GCM,data:fZypa8M0vsWAue+D1Uru73FWKSfE0NNGoIO9z/YHtSF8ynD6d/3ygFCqKZaDXJ6ehzOT8xNJ2Aalmo2IjyQ1dMilt9TWS/DGDS8Fi5ddkoDYDpxoiA4zUeTaO2bKsDU3B7PYvbJqjvwPRr6obKLKXglwlSjk5XlIewzCpreJ1q4=,iv:z55cLGftFsVUXjMce567qiri3vutusqdNIQPA2EwJrc=,tag:fKzPVrVfFIEDEK2KmVNIhA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
