---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 15m
  ref:
    tag: 5.1.1
  url: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
