apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: seerr
    namespace: media
  values:
    image:
      repository: ghcr.io/seerr-team/seerr
      tag: "v3.2.0"
    env:
      TZ: Europe/Amsterdam
    resources:
      requests:
        cpu: 25m
        memory: 320Mi
      limits:
        memory: 512Mi
    persistence:
      config:
        enabled: true
        existingClaim: seerr-config
        mountPath: /app/config
    ingress:
      main:
        enabled: false
    route:
      main:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - seerr.next.bo0tzz.me
        rules:
          - backendRefs:
              - identifier: main
                port: 5055
