apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: seerr
spec:
  interval: 1h
  url: oci://ghcr.io/seerr-team/seerr/seerr-chart
  ref:
    tag: "3.10.0"
    digest: sha256:98eb6df0996ac66488ba57ad0c8287e6f56b094edcdb47763a6bef44abc606e2
