apiVersion: v1
kind: Secret
metadata:
  name: pg-migrator
stringData:
  password: ENC[AES256_GCM,data:N4rB/8XZ+0TvL/Hg7ISaEYfRUSrlEy6vxQQldFc3R+aZ6ZXK+oS1rXT1SES73YzGh1DO1JAV3O25g8bvXROzWw==,iv:YS96iXkjEC7yQveApnH5/cTMF3zTc06wR1o/dOzmbv0=,tag:AQDil5YPrRxBscjAI25zJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZXJmODg5M0plTHdzcC9M
        MVZMaDBhNDFMblU2NWpZM3dkaUxlY2dlQ1hJCjN5S0NqUm5KWG1CLzJiZUcwRnds
        SXRRQnd3U1Rua3JlRThEUE1KallRa1UKLS0tIERxYVVwZ0JocE5Id01GMjkyQ0Nj
        Z1hHTWZQL3FySEpJTmI1U2lkeWFGajgKwo5fP4tNXPqlXP+M4nkUxazbMq6aidtE
        zeN6WOJVd3FYaSWuc1AGJRy/jxeHFWF8Ro5eANL4ipLmVMw9GCHhyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-22T14:00:01Z"
  mac: ENC[AES256_GCM,data:yeNUTKAqaAXaixCfl+gRqAo6k7/jRorPoU7a0dYgRaQZENVuTkqULh/4/PK6kOhCWH1wZkvXclxQqs/7nDtQSLb9+vnzBZ6oboscnL66P6ZfvAFrgR0VnVU2HsaMNCZUiym1CxSlN+kDZuHdJ6wnC15R2vRgcOzFtJyAQdBP550=,iv:X+BTD0SSdvXdFMQu+TsdQDxQKPq8reF4T9Z49K0Sys4=,tag:otsWJpGcipXg2niD8j7+QA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
