---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-migration
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${APP}-restic-migration
    copyMethod: Direct
    cleanupCachePVC: true
    enableFileDeletion: true
    capacity: 50Gi
    storageClassName: ssd-block
    accessModes: ["ReadWriteOnce"]
