apiVersion: v1
kind: Secret
metadata:
  name: kiosk-secret
stringData:
  KIOSK_IMMICH_API_KEY: ENC[AES256_GCM,data:GtQNYLxlC0bU8pP4XRsrrHcNjW1hKVVLlRBwOfy5T6p94X86pIzmUze1ng==,iv:XsjQERYzWanXFikFpVaO4VzEYDNVQB/ge6rrsGvFSLE=,tag:HS9WqrxzBoaJfj5rioRAWQ==,type:str]
  KIOSK_PASSWORD: ENC[AES256_GCM,data:tx8HugInzJMA6YnLgs/jT7r+NjFAgQNf,iv:vNfumVcK+7lsR/QmWgGM60Erx+lkkN0FOASPURJhcOo=,tag:PCVLFJZ/Q6LXjqi75pr4SQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUHFlaCt3MWpobjhXek5N
        a0lTbFBTYnFlSnJOSWlnUUhXNHU3YWx2RFJvClovQ1JMYk90L3pPSGd4bWduUm93
        c2xJTEpJTGRNM0wxeXpma1hHbXpyTWMKLS0tIHdVRFNWaWU3Q2NBZXY5a0Q5TEpl
        SEltL3hiUFFFVkNWeUgreVQvY2hoWjgKC/nHRi9mm5zwjA7L3OC/OiZ29FBZIeFu
        Jk/l+aftQcyWIVSNfCb3Udo0+viBF+AdOXIlkWEp7mAZVhs+QNf9bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T16:28:25Z"
  mac: ENC[AES256_GCM,data:2nbDcwwaWqewWAVD/vEt1zS4mJJZ7MCdTrjIdZXPn42mL2IC2ZNMK3PuPekYdsRZkJZ9fCZuH0CSGevSIphvjGVI843YW9n7lDzU0CCpu+CP0EaJ9OYafTbrtu/uSrwPLqUcLl6knkBQNeiUxOV1J8z2LC4QF40rEjjPHnOYOVE=,iv:eKaqcp5EaAUTpNr89AE+Pep3KUwN3HkTQSxsVG8dWlk=,tag:/VGSNekc7G+awtdnUkgKMg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
