---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bo0tzz-me-production
  namespace: network
spec:
  secretName: bo0tzz-me-production-tls
  dnsNames:
    - "bo0tzz.me"
    - "*.bo0tzz.me"
    - "*.next.bo0tzz.me"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zijlein-de-production
  namespace: network
spec:
  secretName: zijlein-de-production-tls
  dnsNames:
    - "zijlein.de"
    - "*.zijlein.de"
    - "*.next.zijlein.de" # TODO: Remove after migration is complete
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
