apiVersion: v1
kind: Secret
metadata:
  name: continuwuity-oidc
stringData:
  CONDUWUIT_OAUTH__OIDC__CLIENT_ID: ENC[AES256_GCM,data:fnGLU11Z+Qh8nKGmXQQuy5QnqOwtof1ep5r67xIZIMwKYuNMj4mETQ==,iv:aJuQhozj/+0JjiXgUwKGJuWcnfcjDL16bkHMBdAf8cI=,tag:upix5i+yWtf9ktvDEUSaHA==,type:str]
  CONDUWUIT_OAUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:Eo8ZNMTeSbRmGz49f0u92Ujq8soFryh3cVaQdkH/+W1L1MUZ9aNrkjeNFedTS10P7rtXy3OkihY5+wr0aC9lvL9RDsjN0fW5VTQ62ZfxL/Hyg0SoP13EVHZ3PZCLb6WdRR+cP5LwEi7OsNS3y0XI2mdWRmoL+vhezYsdMU+jbn0=,iv:YqsNDOByKoV6sioxlk1xatHGF1US24muXq316oJs6s4=,tag:v39akDUM8zGDwuURe8vUdQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVFg4YWFENXFFSWorV2gv
        TGIwc25JaWxhbTVNbUNoZzV6Z1o1NExhc0MwCk9VMDVZVW9uYTdTTHczTGhtRmxw
        c01XeDlHTmZUSFliQ1JveFkyWFlFdG8KLS0tIG10UlhlMmxuTGt4dzRHdkFVTnV2
        dWFHSTVFcWFJcmdvN1NLdzlWU0hxNm8Kt0cDZ/cbqR1IjiI2o6t6VEhegoDCzkPd
        EsyOWOf2137DQDezAgXGmm99kVjJOtZ4X7RCJMH45AOwQykq/9fXDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T13:32:43Z"
  mac: ENC[AES256_GCM,data:rgc/d2S2u7izM+StV9g2MFxUsUiqL4Cg3qBhPzGOMTIHEjTaRNOTaED8TU4b+sqLMXVQcAbPamd7JpCOYUIzss8CeEbk94kT9VBZKwSQR4nV5qM8HWu6D6UUoqelUPx6beC/0kCY4J2dDdkOAJiNCA95flSH2nmAmsQetSEyi8U=,iv:H4Hd3VFy74qYSKK4oJvHe8jbS0wk0Vyok3ktkXMe18w=,tag:CXCnY1ds+8zOcA1s4BqmvA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
