---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xpumd
spec:
  chartRef:
    kind: OCIRepository
    name: xpumd
  interval: 1h
  values:
    image:
      tag: v2.0.0-rc.0
      pullPolicy: IfNotPresent
    gpuAccess: dra
    prometheus:
      monitor: true
    grafana:
      dashboards: true
      namespace: monitoring
