---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: xpumd
spec:
  interval: 15m
  ref:
    tag: 2.0.0-rc.0
    digest: sha256:a4aa8fdfb2b30a8ab08143fafebdb168ed0899407eab92ad0ffca64c21138b9f
  url: oci://ghcr.io/intel/xpumanager/charts/xpumd
