---
apiVersion: v1
kind: Service
metadata:
  name: share-smb-lb
  annotations:
    lbipam.cilium.io/ips: "10.0.10.106"
    external-dns.alpha.kubernetes.io/hostname: ganesha.zijlein.de
spec:
  type: LoadBalancer
  selector:
    samba-operator.samba.org/service: share-smb
  ports:
    - name: smb
      protocol: TCP
      port: 445
      targetPort: 445
