apiVersion: v1
kind: Secret
metadata:
  name: samba-users
type: Opaque
stringData:
  users.json: ENC[AES256_GCM,data:E5pnteM5lHRvei2CUl8Fb9x2fSFWxp1ncibUY52tqMKRYLp8gkKmGsUx70AHC0SuA9SswCcPpKF8cYUCVRYWXpyXd2dZ1vShQ68HuCqb7CPena0aNNZz58REoAr3tPCtInKBabmP40wys0VkoeCetP8sj2e0R71V1KnNVmyKHB1N6T8KPSHe2mMhl31/ueoI+hiEIr2G0XGcHHLfXW6zZAGYvsJmWBiiF9OKSSvoSewFUwGpQnJrsVoYy2sBcpGfVDMWe6/VQheE3+5zen9QGKKmhJo=,iv:SEf+EJkRY5IUwt5kdmJJHNTeAzbukc0/4wR3941mB7Y=,tag:DTwZvsTmqtzHRLgk8XEn6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QTNEL1RocE9ERzJmdmpl
        akxiVmJWYWNJVkZsaFhYRTlabUMxTVRPVzNZCngvS09lalI4bVNEK1ZmVmR3T2pU
        UzRrb1dWN0xKWEN4Mkd2VGEwLzNHNlUKLS0tIHUzOC9oQlIvWjFEckNXNjgzVWxh
        Nml1cXQ5c2R4SmV2WWxrVGdoeWgrSGcK7dvuZX38c5k9WfzbnxN9D1cjSKU/UaS2
        9TgYvg6N/T4rkfu1PxsBFdRBjdO+8mM/j0rOVhblVme5ribwH05Mqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T14:17:16Z"
  mac: ENC[AES256_GCM,data:vICoOAJ2uo1tCoQ8NVze55auCaB1MqJWkPF5a/8wsdJd/iyXKQVKegi0NWsD5P/KgYMjoaNHXg1l6XVKTijoA1FfTaq0sWhC8+qIadp6UKuBeJbJKKkU0rvAgq1QjNQq++rTohjPH6waov7EqQc2NVs5rho5kJsoowI7vvVQuaw=,iv:6+Sx4JxUDOdihOXP+WH/X7hfsgzyT/ylqK13XXz48r0=,tag:SY7nQ+effUeTuXaP3SHBRw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
