---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keda
spec:
  interval: 1h
  ref:
    tag: 2.20.2
    digest: sha256:f6a4126b9a760fc85dbc62346aac142223afd0955dc042be574c569119b05998
  url: oci://ghcr.io/home-operations/charts-mirror/keda
