---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keda
spec:
  interval: 1h
  ref:
    tag: 2.21.0
    digest: sha256:26bd1e75796532a074cb0b557d6132a9cf37e120f47faa967ef1beb18d7ce9bf
  url: oci://ghcr.io/home-operations/charts-mirror/keda
