---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-kopia-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: kubernetes-local
  target:
    name: ${APP}-kopia-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_S3_ENDPOINT: "{{ .BUCKET_ENDPOINT }}"
        KOPIA_REPOSITORY: 's3://{{ .BUCKET_NAME }}/kopia'
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: ${BUCKET}
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: ${BUCKET}
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: BUCKET_NAME
      remoteRef:
        key: ${BUCKET}
        property: BUCKET_NAME
    - secretKey: BUCKET_ENDPOINT
      remoteRef:
        key: ${BUCKET}
        property: BUCKET_ENDPOINT
    - secretKey: KOPIA_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: cluster-secrets
      remoteRef:
        key: kopia
        property: KOPIA_PASSWORD
