---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-dst
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: ${APP}-kopia-config
    copyMethod: Snapshot
    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    storageClassName: ${VOLSYNC_STORAGECLASS:=ssd-block}
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=568}
      runAsGroup: ${VOLSYNC_PGID:=568}
      fsGroup: ${VOLSYNC_PGID:=568}
