---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

components:
  - ../../components/eso-kubernetes-local

resources:
  - namespace.yaml
  - ./immich/ks.yaml
  - ./kiosk/ks.yaml
