---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    installCRDs: true
    resources:
      requests:
        cpu: 25m
        memory: 192Mi
      limits:
        memory: 384Mi
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: external-secrets-webhook
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: 10m
          memory: 40Mi
        limits:
          memory: 80Mi
    certController:
      resources:
        requests:
          cpu: 10m
          memory: 80Mi
        limits:
          memory: 160Mi
