---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./receiver.yaml
  - ./httproute.yaml
  - ./webhook-token.sops.yaml
  - ./dashboards.yaml
configMapgenerator:
  - name: instance-values
    files:
      - ./values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
