apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:45ZuQutpv8jMXNzRqW/f9nCl1MzRKabj0+sAU/sl5LTdKcUUbw3aTEIAi7k01NJiXzRhW3mK0f0olo639RTFmA==,iv:AwDfTg8XJLZhH94M6bNubKP2PrsL7y/Jyw8Z2pudUUo=,tag:K4JSrdn55s3RgAEEfZHgjQ==,type:str]
sops:
  age:
    - recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bUdmdzlZcloxWGxlUlVw
        S1lxd0JDNVg2VU5Ga3dnWEE2REJ4ckpEdG5RCjlFV0FUbHJrejVkaWx2RkNtNW5G
        VFkxUHppMmYwb2VVbXJ4eHZZcEdjRVUKLS0tIDgySXpiRnloVXIrVXRsVGdDMzFM
        TTJIVXJJVnhHazVtODdRWDVxemxCVlEK1n/zehMV7Relzf7UMlpa1TZNim0J4NV2
        +Ewa79n+0ogF2jay5GOFtXEyjIS+XJK+W/v+7fNzC2tP10l+3oJsNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T12:48:17Z"
  mac: ENC[AES256_GCM,data:ZfGHcLoFXDS4/4G+HrGZWT41LHP4NeLu7IoEMVX0k8xJOEvtnB03u1hvYKLPcvsKVNtKcQfcaenEWQHcD/Fmh5lWTieotE6VymDDO8xqtdh+3XoU3jDSwXNFqcLLcN5KSlqaVSeaNwoJHBRrW8BRrIm8GdUVnfNlw4guGEIlOxk=,iv:h+4rHxp1CsTb0a7caMRHye2HrjRnspVifdJpLK4RgVQ=,tag:w6xmJ8wPdfTxyAt/Mof9HQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
