{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zigbee2mqtt_temperature{topic=~\"zigbee2mqtt_sensor_climate_.*\", topic!=\"zigbee2mqtt_sensor_climate_rack\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zigbee2mqtt_humidity{topic=~\"zigbee2mqtt_sensor_climate_.*\", topic!=\"zigbee2mqtt_sensor_climate_rack\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Plant moisture",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zigbee2mqtt_soil_moisture{topic=~\"zigbee2mqtt_sensor_plant_.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "zigbee2mqtt_temperature{topic=~\"zigbee2mqtt_sensor_climate_.*\", topic!=\"zigbee2mqtt_sensor_climate_rack\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Plant moisture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zigbee2mqtt_soil_moisture{topic=~\"zigbee2mqtt_sensor_plant_.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "zigbee2mqtt_humidity{topic=~\"zigbee2mqtt_sensor_climate_.*\", topic!=\"zigbee2mqtt_sensor_climate_rack\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}