---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperwork

components:
  - ../../components/eso-kubernetes-local

resources:
  - namespace.yaml
  - ./bo0kkeeper/ks.yaml
  - ./paperless/ks.yaml
  - ./actual/ks.yaml
  - ./scanservjs/ks.yaml
