---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: locplace
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - admin-key.sops.yaml
patches:
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
    patch: |-
      - op: remove
        path: /spec/bootstrap/recovery
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: replace
        path: /spec/instances
        value: 1
      - op: add
        path: /spec/enablePDB
        value: false
      - op: remove
        path: /spec/postgresql/synchronous
