apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:yW58VNhuwXQ0QgedAH5qar/WVTljzUDBXpssdCC3v5JzLYFNsTzwn+ytmyvNcCeJBt3qFinBkWuWHO2sgax+zg==,iv:Rsz6K4xy08NLPxpYMjVXYp53qs8Six43JHv1nT1//wo=,tag:OshuE9yM5zFt2NTOJVrF6w==,type:str]
sops:
  age:
    - recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR1RTQXdiWjV2WGkya2VY
        VW9KMFlRTWZ3dXlSWE9YMWkzaUFDZjgyZ2dNCms2L29sOXR1U0cwTGI5UmFRQ2tp
        SFNUODJVUVM3SDdEMXNEWTZud0YyRU0KLS0tIHNaWldYcjNEeSs1dm55YUtYVm9H
        NEw5M3RLa2hIS0hWbERROUxwbzVnOXcK7xssowl8XrkeT6LoebJvh9yQvtf2iBp3
        IuHAI+0dyPRTYISL6yKCHyHOnLLc8z9ancrxabRp1p0H13G/f1sBDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:22:26Z"
  mac: ENC[AES256_GCM,data:Jwb6Jb8F7rgSOwSNNoKVs2UG7d82tgP3QPq3iApptLPwPftMEdJxhfjena2R+cW504vVdvYkXOIL/uDVWyDzmLlhc78jAug7cNKui2wxvFq1GwUypyjqgcJeI1/+QUsFyU3KILK5KH6KjsrqVLjI1el8qdk2t6i8Nk1SZXGW298=,iv:vb1Q3wWLfKNXDWk+RGXrOggP90f0cVLgKGzak7TAG4o=,tag:ocHhdspiu9+tuWc63luQcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
