---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: 5.25.0
    digest: sha256:ae311e8675c11a1d12112eb45676415a797f9dfb7eee91b82f422b53d7c7ab6d
