apiVersion: v1
kind: Secret
metadata:
  name: zipline-secret
stringData:
  # Must be >= 32 chars in v4.
  CORE_SECRET: PLACEHOLDER_REPLACE_ME_AT_LEAST_32_CHARACTERS
  OAUTH_OIDC_CLIENT_ID: PLACEHOLDER_REPLACE_ME
  OAUTH_OIDC_CLIENT_SECRET: PLACEHOLDER_REPLACE_ME
  OAUTH_OIDC_AUTHORIZE_URL: PLACEHOLDER_REPLACE_ME
  OAUTH_OIDC_USERINFO_URL: PLACEHOLDER_REPLACE_ME
  OAUTH_OIDC_TOKEN_URL: PLACEHOLDER_REPLACE_ME
