apiVersion: v1
kind: Secret
metadata:
  name: zipline-secret
stringData:
  CORE_SECRET: ENC[AES256_GCM,data:HBZsTUNbl8a60yM5t3487HFf1JB8EKBYpFqYx2QoRqEyAthoQRYHjL4ufPI=,iv:TAU+VCu4beYaqvdpFK6CnXxGwhiJ4J5kiDs7qKCFvJE=,tag:wTcu9tQvmAPFz2YalKAvjQ==,type:str]
  OAUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:t6Pqgb6D/sdEw2baIKYNoPvzFXnRVo/cqKTo0frfpEnwvFr+HN51vw==,iv:hne8wqkOxRoTcTwCQlC8mgPrTPZ53dhuQBjP21as1tU=,tag:2BZiYUjqy/qkVBIwAqbwHA==,type:str]
  OAUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T9jFbVoRaXj/ti1YQnoYM+ZIhiiFUruyU0CwHr29Lg+ntxGNQv23Vt2vhQpwJZYZY2+zCOeemdxyUrPvWnheAa57LGEzD8YbvbZuQP/27gQrx5DpDJTSrwM2qpjl7h5DPLrbSyW33hGI8OA6gfQEWtWekWQdNGRoZX6Vd25tTb8=,iv:F45iDJ/1QSY95BLHvY4b6RGnkhewaImeFhRfF8U+44M=,tag:i1T1xO5H+KNTG7Y2jwAu9w==,type:str]
  OAUTH_OIDC_AUTHORIZE_URL: ENC[AES256_GCM,data:zpys++fX1As0mwCx0J7K1EmWZhpW++K2UgtD73PkQ6KjC2a2Op9eUB1AyqVbDdc=,iv:eWtRsDIlJntV7/N9LedArhmTkh2KU9k3/lJsSJG8FHY=,tag:Vkb1PNrzpezsg6rpIBU9ug==,type:str]
  OAUTH_OIDC_USERINFO_URL: ENC[AES256_GCM,data:wDa9YUv5EU7LgR/The085Yc4WinEdcto6V4Cpa4zshMJ+lINKwPBnWoj7CAL+A==,iv:xAgB2V5pXvVXmc/lvIEUpFsLmWBj2VfhQ9dB3ykIjRU=,tag:8midTMCbDHGdg3seW4dHkQ==,type:str]
  OAUTH_OIDC_TOKEN_URL: ENC[AES256_GCM,data:BXCd0fURFpo/J5Sf+wI1ac1AJ6NMb6dlBdy4Y/rhdpY0wDTTQb96mFfsrw==,iv:YJLfcRMoZPWFcpybhoVoWiHZzS2o4DPSSlk0UHV+5sY=,tag:qBhY2+NwGmgVJiBeSsaD4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMEZGZzdtdGlrbDIxbHFG
        MjZyTmN6aDF6UitBY3YxMDQ5N0tWUXhuTTFRCllYaTI5cTBqRW5PbXlyWFZPREtR
        dEU4RnRhTlJYNlRzcEg5VlNOL1lJMFUKLS0tIHJGczF3ekU2MG0zVi91WVFlQzll
        UzR4R2h0VjV2M3lKb1N4anlYSVpTTnMK4y5hqSwukX/PwMFyz+0FhyJgG4XUKNYh
        LjJprdiyI0lXIgA0E7vJHAUHEKsaD/QCssFlBylxK76bpDSwWZ682Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T18:40:49Z"
  mac: ENC[AES256_GCM,data:rhdse2SP2d7SiJTzr3uNOudak0vLlg38DcaH4A9kjrzyP0TsFWDsYmZXXYE9GsGFxD486nHP5c2BQrf1Z/4KsasSLPzju7L1pGiN2D78VV85HYJMFfw1n96tsUWpDJk7C4e8eP5XCk+lKPWbJBJJv0SNAJ4aGra6wr2iiwkhUUA=,iv:TRId1UyKz7KiXka+LD1uBixQrYCacSxS1iUq3tjDIm4=,tag:bDg5MhzAY8wB+vBQHtlCHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
