---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/374ca253808b19d013e41028ca4246d3d4fc3be92c19f5dafcb4aa2f39625c1a:v1.14.1
provisioning:
  diskSelector:
    match: 'disk.serial == "23294BEE1C17"'
  wipe: false
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: tiny
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: trunk
selector:
  match: mac(link.permanent_addr) == "58:47:ca:7a:bf:e7"
---
apiVersion: v1alpha1
kind: VLANConfig
name: trunk.16
vlanID: 16
vlanMode: 802.1q
parent: trunk
up: true
addresses:
  - address: 10.0.10.14/24
routes:
  - gateway: 10.0.10.1
---
apiVersion: v1alpha1
kind: UdevRulesConfig
rules:
  - 'ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", ATTR{device}=="0x46a6", ATTR{sriov_numvfs}="4"'
