---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: home-assistant
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: "2026.5.4"
            env:
              TZ: Europe/Amsterdam
    service:
      main:
        controller: main
        ports:
          http:
            port: 8123
    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config
    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - 8a.zijlein.de
        rules:
          - backendRefs:
              - identifier: main
                port: 8123
