apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prowlarr
    namespace: media
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: "2.3.4.5307"
            env:
              TZ: Europe/Amsterdam
              PROWLARR__APP__INSTANCENAME: Sonarr
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
              readiness: *probes
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: main
        ports:
          http:
            port: 9696
    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - prowlarr.next.bo0tzz.me
        rules:
          - backendRefs:
              - identifier: main
                port: 9696
    persistence:
      config:
        existingClaim: prowlarr-config
        globalMounts:
          - path: /config
