---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: imagebot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: imagebot
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/bo0tzz/image_bot
              tag: main@sha256:99ecaec9251002d2e13681e2f501feed9f7d51fc4cd82d86bd3b47fa2fced037
            ports:
              - name: metrics
                containerPort: 4000
            env:
              KEY_DB_PATH: /data/keys.db
            envFrom:
              - secretRef:
                  name: imagebot-token
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
            resources:
              requests:
                cpu: 20m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: imagebot
        globalMounts:
          - path: /data
    podMonitor:
      main:
        controller:
          identifier: main
        podMetricsEndpoints:
          - port: metrics
            path: /metrics
            interval: 1m
