apiVersion: v1
kind: Secret
metadata:
  name: imagebot-token
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:l75oyn/FEUU2SEgfqkXNPTFDdbMnzmnwZGRem7mtk60m/c2Md2m6D4TKAN0P,iv:4dym2Ytw/vFZ5ZxqUKp6aZUOkR0BiEKUX6qc8aSCAZA=,tag:SlKbPE3UVaxKxXyxEtRBqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2lTdWM3amtUcFo0Qkli
        VzZmdnp1RFQzeklnSTBBTWI0c21JYVFSSEFrCkMrZmxHblhvMkFyb2lIaSs2c0hz
        ZVprSDJLWERtZFZxRml0TmxVMzQyYTQKLS0tIFlYeFY0UlFhRC9vWWJlSmI2VmpM
        NXZpNmxpZDFtSkl2Z3R6WGtTRGU0ZncKVrFzoSYQ8h8gaJqE6rl056/3y1l5vstx
        KTtOaExGso6WAXcQW5ql3JyMrjKgh8avDwF2luAC70DR+smsCJJHHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T12:04:10Z"
  mac: ENC[AES256_GCM,data:Em8vxhh81r/9C05vt+ZuN1A0KkdbzbuVZPB5A734IeZBDVgWzoHnIAFsbkb+qbnrcrqG20ia3Lppr5sCxzldOPR5m6bKkPljeHB7WMSP8d2OM1AGWtR/1vo2SMEnUXofV3JJ2z+ZIBtScaKpUzkMafXvC8WUp8piiwHpznyIZDY=,iv:DsyQeLC+S0d3XfBQHbVoJOqrhZ5rVClE7JRF4nEbzU0=,tag:f37rrnzdcPJ8YSRAKasOgQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
