apiVersion: v1
kind: Secret
metadata:
  name: evcc-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:RE172F5WsYq9vBd+W8FI80U1VH1dA69iuUxYYkAGm5TlHc3GS1s+yw==,iv:mNdBbrBBSnl5HftWm/TOBK5KbXttS5fuJG/61JVDFG0=,tag:OzaErRxs5QIPBxcfptJJyw==,type:str]
  client-secret: ENC[AES256_GCM,data:cXVNSBXb7ZV4omjIkQvyF/fdHN3M0QYSOdfuyEFzDImOrWcCZYyYtcMXiaVc6mMsbvNZWu1JN8nNCk9LiCjLk8ne0ayPO3COaN8CBe+Mx5wchraluxxoo3YzfBtWZEZjH7NldGEgzaoDDF1/3vDekoQk3mDJdgidh+GXPYlv9PU=,iv:HZOZuX/ja0lut3kAf5CLVJWgvTfZEPOfmYVqYlv5b0A=,tag:GTQILsfRLwVeFDYBMYQbgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QTZxY0UxZ2swTFRma0xp
        ZXhEZ2h3dnFFbFdhalR1WmdRSWc1S3VhSFY0ClJiN2x1NEU1V1BBNXYxQ1pHM0Z0
        Z3YxUkNxS0VBQVhnR2p2anlSb2o0VmsKLS0tIExxaFZkU2lnQnY4NytPZzF6VVhY
        eVhVRFFjNENPTmRVZkpRdmdrQm1CTkkK7YNVwTADWP2nMbaPFTCMz74iK6a0+DJv
        4mf97U3/ufrMSKDP1twqOZ3ktiUGP8vdc8NwLxTyUw1/U4Dg0JQLfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T17:54:44Z"
  mac: ENC[AES256_GCM,data:SRtWY8Y3gnT4u5AJidQPzXBeNBG7apcVvnWU2VuiGLunMzLfE52TCS5qIyDkPIrbBYOeiIK27B/TzMcQHz/rfP9b6xop6rbSwwr8OgSmvkev+3xrwe/SfRsB5AKVskYwjlhYqRMG7BW2Mb5v0fdzpUZdOg9MoFG0iK9rXhnhzgE=,iv:CfTJOsTeAuB8a5X2s2q4CANKum1P2UnJsujpWlpNJWI=,tag:zv9+QmAAayOqyRFkx914pg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
