apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: stirling-pdf
    namespace: tools
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: "2.11.0"
            env:
              SYSTEM_ENABLEANALYTICS: "false"
              SYSTEM_ENABLEPOSTHOG: "false"
              SYSTEM_ENABLESCARF: "false"
              SECURITY_ENABLELOGIN: "false"
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - pdf.bo0tzz.me
        rules:
          - backendRefs:
              - identifier: main
                port: 8080
