apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: media
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:itKgmn1nxsyMx5vzGij8tA+0NRTyT4lY1x8n9gMk8DTUPmDAM4Ae/LyPDB+IzNRUCK5Bs9wFWeDYSYjITDzrgg==,iv:fTD5t63s4R2nKWcNVPURvyAUs+wTOiR316sLzr9XV2M=,tag:qE+M/PpqjTVUoQdQPhjQUg==,type:str]
sops:
  age:
    - recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRGs5MytuempNUk9CVk82
        OW1LbTBWckJQR1B3UHV6NytKTkxiSm45UlJ3CkFobUxlZDJUMVpVRUk2NmJjS3pQ
        K2ViVlNTK2JPYTNCNm11ZlFyTXE1clUKLS0tIEtmUTBMQzNkR09OUWRGVnVER1hL
        MFg2OUtGTktvWXMxbkYzM0NqUHlxRGsKjk9Ml+ZesRTPqLvZaY99pGNW6O1tDSS7
        nEctLQ1ppmpx1BtlORl+6s4ioixkIoGV/TbtdSxibe2xNsWbpEtH3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:21:36Z"
  mac: ENC[AES256_GCM,data:Ke/EcpvlXAXY00c5gPKIrASdjYTKnLkq+vaxNxld2F8gFNUAqxC/icEZnOHm4iN9BUXr66JbKGk/JIBXjTQbnpFLgT5FOUiZGO5+Uhh9QpMpKyISyEz9uOKdHp3FygOC3Miaktm+DnSJEuidB8Np98YBhqn4u9eIT7S8oCauzdo=,iv:7K0cATzTSLv5XaOBUrXwWCWCdd8Q2ryPsoHPNLiRD+4=,tag:NJajDzlGMQxcUW7pdW01Eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
