---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: old-cluster-migrator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: old-cluster-migrator
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pg-migrator
        property: password
