---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-barman-cloud
spec:
  interval: 1h
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  ref:
    tag: 0.8.1
    digest: sha256:b48511269e2c75603ee2f06f6c5444e8154542103a3c3b9d692344725bac37b7
