---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: smartctl-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
  ref:
    tag: "0.17.1"
    digest: sha256:3b205562ffcb1fc6228c9216b3f1b1d6451e647cb73d02548c402e780ac8289f
