---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operators

resources:
  - namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./cnpg-barman-cloud/ks.yaml
  - ./external-secrets/ks.yaml
  - ./keda/ks.yaml
  - ./keda-add-ons-http/ks.yaml
  - ./samba-operator/ks.yaml
  - ./volsync/ks.yaml
