---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperwork-paperless-bucket
spec:
  interval: 1h
  path: ./kubernetes/apps/paperwork/paperless/bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/bucket
  postBuild:
    substitute:
      BUCKET: paperless
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperwork-paperless-migration
spec:
  interval: 1h
  path: ./kubernetes/apps/paperwork/paperless/migration
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationDestination
      current: has(status.lastManualSync) && status.lastManualSync == 'restore-once'
      inProgress: has(status.conditions) && status.conditions.exists(c, c.type == 'Synchronizing' && c.status == 'True')
  postBuild:
    substitute:
      APP: paperless
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperwork-paperless
spec:
  interval: 1h
  path: ./kubernetes/apps/paperwork/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/postgres
    - ../../../../components/volsync
  dependsOn:
    - name: paperwork-paperless-bucket
    - name: paperwork-paperless-migration
    - name: cnpg-barman-cloud
      namespace: operators
  postBuild:
    substitute:
      APP: paperless
      BUCKET: paperless
      VOLSYNC_CAPACITY: 50Gi
    substituteFrom:
      - kind: Secret
        name: paperless
