---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: share
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - configmap.yaml
  - securitypolicy.yaml
  - oidc-secret.sops.yaml
