apiVersion: v1
kind: Secret
metadata:
  name: copyparty-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:9aYXFqAUC2FkxQxS5xCePcBkGUx4c4azaUAO9a3KaHPTW9n8azmmew==,iv:c1q3T4S6mtcSNFO8EVZt1n3k1QM/6EuwCOUvNXKnEVM=,tag:xS7v7dF6C92iUGuK2HyM1A==,type:str]
  client-secret: ENC[AES256_GCM,data:O7Q2CO7zjh/P4vTxu4E9XN4409eG9WI9SSRxQc0mL6ymg3f8R2+zWX1c+LzQlBhxh2eHDmxCMyV5BE+yMHw7ZBlptgODjWvsEishwiYqRSTaoslU19DPUfeAx0HCK/Cdos1YJEHilMirdqDWvTVxL+bepPvxggOLD1ZlRw9xpnU=,iv:3gfwbpPbiw0Ny/7DADcCX8yZb2wmouXwbMC1ijPs/pw=,tag:azxaDSjp4cvpbIyxl8xqDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ak9RVTdiNXhnLzlDYVkw
        cUhvcE1xME9KWmxpVDlTRElsNkhYbkcxTkVVCjVqcnpjNVNnYktmVVhBaU4xWEg0
        bnZFQlVjaUxYVmtIOTUwSldHYmJDU2cKLS0tIFVVZDR4Yi83bEtNVnJYVTk3Ykty
        SWNyVDM1TXU2Sng5Q0NHTXk0Ui95YVEKxPRsZz8HvrvN7w4InRkcTXAhaiGYLwrF
        cdqtgHWV/MtIpXhWdVXT9yRC1qpfPo+XKbCznD3dgtaWCr8cOvcwkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T12:01:12Z"
  mac: ENC[AES256_GCM,data:MIaLS/8GHvr8XIY7FE7cntJSthK22WjDgCRwpfx3HWNDF9L0K5fj8LDp3yUnBJmOqiFWJt6gGTfGvAwpYJypvoAHWDrcvK6cPp7JyHN0dny4UvoRLPGCR2caCZj7XzrVKVLdLe9+U0LnBCd8uNyQKYJTGq/Pb41QyrcDcQUa2Kw=,iv:Z5JrU/IbJii5JGUuB9HdHNZnaz9vcYa6D2HndY/ObyQ=,tag:qXGT0k6VVNp4evC+Q3dt8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
