---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: share

components:
  - ../../components/eso-kubernetes-local

resources:
  - namespace.yaml
  - ./zipline/ks.yaml
  - ./pingvin-share/ks.yaml
