---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: local-path-provisioner
spec:
  interval: 15m
  ref:
    tag: 0.0.36
  url: oci://ghcr.io/rancher/local-path-provisioner/charts/local-path-provisioner
