---
version: v1alpha1
debug: false
persist: true
machine:
  certSANs: []
  features:
    diskQuotaSupport: true
---
apiVersion: v1alpha1
kind: LinkConfig
name: trunk
up: true
---
apiVersion: v1alpha1
kind: VLANConfig
name: trunk.1
vlanID: 1
vlanMode: 802.1q
parent: trunk
up: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 300GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: system_disk
  grow: true
  minSize: 10GiB
  maxSize: 500GiB
filesystem:
  type: xfs
---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.37.0@sha256:d87c090ff7d915c308bf71ad2fe7d63a21cbf8e2481066d2c4b41feea2ddc5c9
defaultRuntimeSeccompProfileEnabled: true
config:
  imageGCHighThresholdPercent: 60
  imageGCLowThresholdPercent: 50
  imageMaximumGCAge: 168h
  serializeImagePulls: false
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  fs.inotify.max_user_instances: '8192'
  fs.inotify.max_user_watches: '1048576'
---
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: cdi
content: |-
  [plugins."io.containerd.cri.v1.runtime"]
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
    device_ownership_from_security_context = true
---
apiVersion: v1alpha1
kind: ResolverConfig
searchDomains:
  disableDefault: true
hostDNS:
  enabled: true
  forwardKubeDNSToHost: true
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445
---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: clusterfuck
endpoint: https://10.0.10.10:6443
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local
podSubnets:
  - 10.244.0.0/16
serviceSubnets:
  - 10.96.0.0/12
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
endpoint: https://discovery.talos.dev/
