clusterName: clusterfuck

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.10.10:6443
additionalApiServerCertSans:
  - clusterfuck.bo0tzz.me
allowSchedulingOnControlPlanes: true

cniConfig:
  name: none

patches:
  - |-
    apiVersion: v1alpha1
    kind: LinkConfig
    name: trunk
    up: true
  - |-
    apiVersion: v1alpha1
    kind: Layer2VIPConfig
    name: 10.0.10.10
    link: trunk.16
  - |-
    apiVersion: v1alpha1
    kind: VolumeConfig
    name: EPHEMERAL
    provisioning:
      diskSelector:
        match: system_disk
      maxSize: 300GiB
  - |-
    apiVersion: v1alpha1
    kind: UserVolumeConfig
    name: local-path-provisioner
    provisioning:
      diskSelector:
        match: system_disk
      minSize: 10GiB
      maxSize: 500GiB
      grow: true
    filesystem:
      type: xfs
  - |-
    cluster:
      proxy:
        disabled: true
  - |-
    machine:
      kubelet:
        extraConfig:
          serializeImagePulls: false
      network:
        disableSearchDomain: true
      sysctls:
        fs.inotify.max_user_watches: "1048576"
        fs.inotify.max_user_instances: "8192"
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins."io.containerd.cri.v1.runtime"]
              cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
              device_ownership_from_security_context = true

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedKubernetesNamespaces:
              - system-upgrade
            allowedRoles:
              - os:admin
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381

nodes:
  # - hostname: sketchy
  #   ipAddress: 10.0.10.11
  - hostname: janky
    controlPlane: true
    ipAddress: 10.0.10.12

    installDiskSelector:
      serial: 23294BEE189B

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/xe

    patches:
      - |-
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: trunk
        selector:
          match: mac(link.permanent_addr) == "28:80:23:91:3a:ac"
      - |-
        apiVersion: v1alpha1
        kind: VLANConfig
        name: trunk.16
        vlanID: 16
        vlanMode: 802.1q
        parent: trunk
        up: true
        addresses:
          - address: 10.0.10.12/24
        routes:
          - gateway: 10.0.10.1

  - hostname: wonky
    controlPlane: true
    ipAddress: 10.0.10.13

    installDiskSelector:
      serial: 25034DD0804C

    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode

    patches:
      - |-
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: trunk
        selector:
          match: mac(link.permanent_addr) == "28:80:23:91:3f:64"
      - |-
        apiVersion: v1alpha1
        kind: VLANConfig
        name: trunk.16
        vlanID: 16
        vlanMode: 802.1q
        parent: trunk
        up: true
        addresses:
          - address: 10.0.10.13/24
        routes:
          - gateway: 10.0.10.1

  - hostname: tiny
    controlPlane: true
    ipAddress: 10.0.10.14

    installDiskSelector:
      serial: 23294BEE1C17

    schematic:
      customization:
        extraKernelArgs:
          - xe.force_probe=46a6
          - i915.force_probe=!46a6
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/xe

    patches:
      - |-
        machine:
          udev:
            rules:
              - 'ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", ATTR{device}=="0x46a6", ATTR{sriov_numvfs}="3"'
      - |-
        apiVersion: v1alpha1
        kind: LinkAliasConfig
        name: trunk
        selector:
          match: mac(link.permanent_addr) == "58:47:ca:7a:bf:e7"
      - |-
        apiVersion: v1alpha1
        kind: VLANConfig
        name: trunk.16
        vlanID: 16
        vlanMode: 802.1q
        parent: trunk
        up: true
        addresses:
          - address: 10.0.10.14/24
        routes:
          - gateway: 10.0.10.1
