---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-bucket
spec:
  interval: 1h
  path: ./kubernetes/apps/immich/immich/bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/bucket
  postBuild:
    substitute:
      BUCKET: immich
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  interval: 1h
  path: ./kubernetes/apps/immich/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/postgres
    - ../../../../components/volsync
    - ../../../../components/gpu
  dependsOn:
    - name: immich-bucket
    - name: cnpg-barman-cloud
      namespace: operators
  postBuild:
    substitute:
      APP: immich
      BUCKET: immich
      VOLSYNC_CAPACITY: 1Ti
      VOLSYNC_STORAGECLASS: ssd-fs
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_COPY_METHOD: Direct
      GPU_CEL: 'device.attributes["gpu.intel.com"].pciId == "0x46a6"'
    substituteFrom:
      - kind: Secret
        name: immich
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-ml-gpu
spec:
  interval: 1h
  path: ./kubernetes/apps/immich/immich/ml-gpu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/gpu
  postBuild:
    substitute:
      APP: immich-ml
