---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant-bucket
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/bucket
  postBuild:
    substitute:
      BUCKET: home-assistant
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant-migration
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/migration
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationDestination
      current: has(status.lastManualSync) && status.lastManualSync == 'restore-once'
      inProgress: has(status.conditions) && status.conditions.exists(c, c.type == 'Synchronizing' && c.status == 'True')
  postBuild:
    substitute:
      APP: home-assistant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: automation-home-assistant-bucket
    - name: automation-home-assistant-migration
    - name: automation-pgmqtt
  postBuild:
    substitute:
      APP: home-assistant
      BUCKET: home-assistant
      VOLSYNC_CAPACITY: 30Gi
