---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant-bucket
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/bucket
  postBuild:
    substitute:
      BUCKET: home-assistant
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-home-assistant
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: automation-home-assistant-bucket
    - name: automation-pgmqtt
    - name: multus
      namespace: kube-system
    - name: multi-networkpolicy
      namespace: kube-system
  postBuild:
    substitute:
      APP: home-assistant
      BUCKET: home-assistant
      VOLSYNC_CAPACITY: 30Gi
