---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgmqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pgmqtt
  values:
    replicaCount: 3
    database:
      existingSecret: pgmqtt-app
      existingSecretKey: uri
    extraEnv:
      - name: PGMQTT_LOG_LEVEL
        value: debug
    resources:
      requests:
        cpu: 25m
        memory: 160Mi
      limits:
        memory: 256Mi
    listeners:
      ws:
        enabled: false
    serviceMonitor:
      enabled: true
    logging:
      format: json
