---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pgmqtt
spec:
  interval: 1h
  url: oci://ghcr.io/bo0tzz/charts/pgmqtt
  ref:
    tag: "0.1.17"
    digest: sha256:1a40583cf8fcc253f58003cd07204802f561c7f3fd7f06f62562c331ef34b7d9
