---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-snmp-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
  ref:
    tag: "9.18.0"
    digest: sha256:4626261a653f065d8692e1562d814c596e0612b8a0647115a0eb89e21dc85798
