apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chartRef:
    kind: OCIRepository
    name: metrics-server
  interval: 1h
  values:
    args:
      - --kubelet-insecure-tls
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        memory: 192Mi
