---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

components:
  - ../../components/eso-kubernetes-local

resources:
  - namespace.yaml
  - ./frigate/ks.yaml
  - ./birdnet-go/ks.yaml
