---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

components:
  - ../../components/eso-kubernetes-local

resources:
  - namespace.yaml
  - ./frigate/ks.yaml
  - ./birdnet-go/ks.yaml
  - ./pgmqtt/ks.yaml
  - ./home-assistant/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zigbee2mqtt-exporter/ks.yaml
  - ./esphome/ks.yaml
  - ./evcc/ks.yaml
