---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-addons
spec:
  interval: 15m
  url: oci://docker.io/envoyproxy/gateway-addons-helm
  ref:
    tag: 1.9.2
    digest: sha256:5ba7a2d5bfbf2c1abad92a2bc282ed204b484fbb6aff566a5b38e80fee5e402a
