---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-migration
spec:
  rsyncTLS:
    copyMethod: Direct
    serviceType: LoadBalancer
    capacity: 1Ti
    storageClassName: ssd-fs
    accessModes: ["ReadWriteMany"]
