apiVersion: v1
kind: Secret
metadata:
  name: memos-idp
type: Opaque
stringData:
  memos-idp-authentik.json: ENC[AES256_GCM,data:zD/bEJPEMTVJ16xN+nU2GHeYDPYM6U6L54hR2T8vI4WCtbbOlwhm9c8FYJmt0REJEb1Ziwh+pTIsqZIYet+aUQtADlGt+rqQDIs+u19KGhxsS4sFlS92pZIZ4slcCX6Z55Qtl4Ye+fiEbTMwGpvVvpkLHmswMzhYQwFX7id9EZ/hW4bbgdqKJtBsFdrcg9TJeJMifOH6HkLJDfefy5j32t1XVJHTWeLpPUV8i+NKKPICZOm49anWXJ0qvVio6Y86Sg6ST9gSXJK/WF2hLpEWZedEQ+jr+LTiWtCq3CqvSuE2qQ3F3ubQ3VKtmaDsoXToZJFJj+FgFoeM+/lQxEbzfUVoocv00nTy2POqghBP8cyx8pcRNpLhbmEFJfA5UHEG8fHi9XdOAfFmefUFROCZRmBP/okW5tQu0LdiwjTDEBIImSXiTnK+BuunPZ1YVS/iCYVDssnSNk6Z6j6JePhhREhW0uwzvzWgCD7oOAWIGFNn9kGRA4sG1wCNla72RwiHrsPgOZff2Gur1PrdpeglsJRYCbbZO0Ocv4rNDVtv9OjlKHE6o1v6HdUYOgfIn4jDX6ZJR3S4HcJ8cS2Eh+k5lqcZbXXDh1jfFQY+VWGqURMgTo8LFc4aqF6ufb3pxM2Ck9UwpiNLZvF6cMWWjkaM5/SLd6lh0yTvmiX9O/RW1ZsaP4W/E8mAqITai0AUC2tCGyx7o/y8drGsERlB2alpfya6Wp07a0zWEayMDihSSCXDAx5JxJt+GDjwmHGieZ85NrvnGT+K1HpulUY96jGD6fg6TvRrWN1Q7kiYjG+d53Ul/FeAQudoHX/RtaR+UwfArkf5HmTEBE/DLMll63ByeZAnu4iTLOrSToqCa+uB5AbRUtGBQaqXg2fz4P2xXVWJWLVIscbW5mSzQiHKSFcXoUGpXwnlCyho3+1JIxl/FTHvHjWl94jzqwDw9teGLcKn2nZSgVsflLo+3K7yra9cDDIS8V9/,iv:eatsoXLVgrLv6TnDLOWvT+zCAwDlRRevlSjnOQ2FK2E=,tag:a/LFcTTYmRWycRvKbLB4jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ085OEZIbmxNYkVpcUg1
        bHluZ25yTVhlMjNtSXpCckludlp3cEUvSUJNClA5UWRESUl0bkVlUHlCa0k1dlhj
        NU00VlA4emVrWDdiUWlGU2tWb0N0S1kKLS0tIDlDQTUvaUI1eHBHSDVpNEtHZ1p1
        ZS8xdUdtMXQ0aWxlSEpsczk3UzY4aEUKhpnyDjABYIwmKiczrZVg4nAzR0SSTz8m
        wGwY2ffc9XVy1vFzQlsHk0FssydvKjlO7IfIcp69VqgQC0Dd4NuSZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T20:07:34Z"
  mac: ENC[AES256_GCM,data:fXOTWyCLDB8b6QE7caQ09EjHWcKAHOiu9Dlu+FXx+Ha8Q4fJUIvCr7+GjT5VBGEFXcXQeTundTbgPzRN9rU1WXXMw+epIhvqELJrDCAuV8swbxIiZLgp7ZoJRvlz82XJ1m5Wia5CCO3dmy0J4voXfp0jwLDD4FIMVf4jd/A8Hy8=,iv:ph5yWRfiz/5gxUUqXONuOVQAbYmb/pmcPiTdgcvgKQs=,tag:quLe5tkr2DibFwiY7n25Sw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
