---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.19.6@sha256:06c54baefed2ead3c3bc71e5f2f057e78ad2700606722b68c2fc73153eab9b64
  url: oci://ghcr.io/rook/rook-ceph-cluster
