apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:jjrAzOysws1zhQQVF/AAhJxwfVuyIflCCNCeIYTNrqvw7ccUte6PTvMDR9nCz/sG/0lTwoTkYfVi0WJ/WhjFEA==,iv:opN/cw0H+3rAhL/NbHmBAtBaMni64dithkwr2nkAmLY=,tag:q51iWUWuK1WKBCrB43Gnpw==,type:str]
  AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:JF67OfOVfVndHUJ2KaNRIv8=,iv:EP1RhBf6yRcUvxzjwImLu8CJgER1jZCRbnilAXqSFLM=,tag:TOjwLj/QCN3wisOLeEA6hA==,type:str]
  AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:GQJhS+s8CFtnhM5m,iv:lN9G10NhQxu3cZeCHOgldnEqceEdIJU5M6+iOl8ZZU0=,tag:srmH6Y0iDLv23HaSJ1CbZA==,type:str]
  AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:+Wr2h/G7XSNHlbLaEVgN3w==,iv:UjZJqWh5qXRHnCe+s64ko4ua02LID67N0qDM47EQcX4=,tag:weTPy1KCd5w/nHpWWfPRIQ==,type:str]
  AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:EJ7wVKWM8EeM5XBLKTq7ifuQ9tS6hh6+uv8=,iv:GyS8eA4yEOUgxFp3mb4MPnuKeDuPJY/rLMlmg1QvkO8=,tag:Ioh/a6qWvBLr+soMpMi3SQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVDlDZEJOOU04QllOVnRj
        aUowNGlsbjdyWkpTTm9JeUNZMHR2eXIzWEcwCnh2dndFUDRKamhkSUJHR3RvdjVB
        bjluOExQcEhGOHV2RHJ1TE5TME1LaDQKLS0tIDBycDNuOTlpd2lBeGdlMldsQlBv
        RnpVeS9MYmk2REJneUV3WXJiYjZJN1EK91j5k9sbs61xV7F/wtierCXqeQWl4255
        ZHyvXSbLkxTuxJ72DYJN622z0JAlOSAPEZUSB28OX7DHAWKP1Xazcg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T07:52:35Z"
  mac: ENC[AES256_GCM,data:HRgdOd4tv8/QAwmt1pC776hz8zLX84+0jvd0H/3wDqphHSUf+5fGUhKFzy9fZQHuGiQI1adxuWob6E8CKQ8ldDHP6FB6i+rNxExU7zhEyhecJ1l8vyD/Oau4oz7iFC2p44X3RLZHGI0SycI9J5ekezTLfU0l7E/mjY391DgnDQw=,iv:nRYwj4bm7R/35j9Sr+eQldb5THUI1i+6NlI1u7y4TIg=,tag:IoNlNX2bGdS3be/BvzUjDg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
