apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-jellyfin
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/gpu
  postBuild:
    substitute:
      APP: jellyfin
      # Pin to tiny's ADL-P iGPU; hwaccel is somehow broken on janky's xe Battlemage.
      GPU_CEL: 'device.attributes["gpu.intel.com"].pciId == "0x46a6"'
