apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-oidc
stringData:
  GTS_OIDC_ISSUER: ENC[AES256_GCM,data:Ou8iGz65rTIeXNr6dRszK4kUmdk652/QjKI6skBnQV3+cquExAX7vpM=,iv:9Y770kB8J0TU822ZpaWbnLu/S709IR6cHqWEowsKYQU=,tag:LSYTVzRpyZfkPPf3VwjjRw==,type:str]
  GTS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:aKEOrGcb7ePReDSVaNePLIrZtDXdMSutuGGAXhzMtMwX/eg1FNtbcQ==,iv:4KOc6dM6I7mW9OUUbgGJ/5U+U0qaRu4ohzTGm8eGk9c=,tag:47aB+8DhG79IvmvS377nuQ==,type:str]
  GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:eh2SFAGXl1OX1bu2i6EUsRC+CkU0lAx/3olwy6vtWYdR3fhMHs7JPIBaCwTegYv65eA27LLbcxazTld9rj16FSDsMPsOuw5xPOD/tKdzX6DEjModWzwZaPcZ6e41uMM0exgQgZeundzfeqjxs83FgtzPAOj+jfKP+nzTBKblDXY=,iv:llLxt61Wox0Oq6eM/EZPtL0qNqOCi58SlQjBKToC27Y=,tag:lbuFZRbKKxe55rRA2WDuqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaDB5SWJua2NoZzd3V2tq
        R2t1aSsvcVA2RFltckt3Rk0rTWxnTWRNM1Q4CjY3aitPeitIYW9KbDJOcEFtbEtv
        NnlrVlJzMXlXSWh0UitpdkVxZDhCMmsKLS0tIDQrdVh3QUxIdGFZVTdrY2o3V05j
        dEdTeVRqTVRxcll6bzFyVnFsR3VndUkKzwbIi7O24wxbBb8Xmo6MtR8YCwr8ySUD
        2r3S6tbIFc8evGd5MifDTilRa1poKwM4I4Vhq1U8aGBzBrSeYWVYDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T19:30:27Z"
  mac: ENC[AES256_GCM,data:K2ZFbahoR1nIR6HmOGMvyQm4sUnw3539htjxRFgdE4w4j4UD6qq6yDEi1p1PoA7CyR1WO8MAtUczJtVrdpkIPYmS6/U+IAR0cANjWms0eCyOW3q4DFpVw/Dioau370XsIEbNWly4i6MwWhrlLp/6kU9gvmeRGC56i3xFMrmCjEE=,iv:Lu4vzvlVmRHHfMwvcckfVPzJSkSO3pKdCpOlDU50s9Y=,tag:BFwJaT2UyuJERYHWyiqw2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
