---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  config:
    server:
      root_url: https://monitoring.next.zijlein.de
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              envFrom:
                - secretRef:
                    name: grafana-admin-credentials