apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
stringData:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:5x/pzyE=,iv:e+HinG26E76GpQdPhJU2eSEUXl79kDgGrzcgj81L8b4=,tag:H57+EsNpsBvHxR+kYM4A1g==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:lnB9Lgq3rOxUqRJJAn1cgw==,iv:ZdTNoNula6LOdBowytZiQk9j478A3kCp7jtq0EKDQkg=,tag:WjcY39uZTs55YDuygSRPRw==,type:str]
sops:
  age:
    - recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdWhBZURVTTNxcGtSTVBz
        bzhLMzZ3WWFFa0V4bkxqeW9ESFV4bVlvQ0RjCmsvYmxMZ0RudWp2TzhVL2tLNE4w
        VW9XZkE4MWlWQU1vZUFWZXFsOXJieHcKLS0tIC9nZk9SVEdoVVNFKytMaWU2RFZR
        RGQ4V3pHaUFEMFp6Q0ZyVVdyWFhiZkUK8JYMS9iB69x7ieBlyl4B2aZhrnUhqrrB
        CCrVHkOLvjRcUxBVmTPdBHpbVhF78qty/94jMaIyDdRUbkN5oKkzXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T13:11:01Z"
  mac: ENC[AES256_GCM,data:UN+yxLvxuxiGzqlyhLCIQGG8oYZqNs6cpfm4ZZ1Ua65fgfTODl3kn8ayiypqSU23g+9Y9HDoB6iXFHzG1sYDYiOe5UPvljy2EbPTyXW9iJ/q9pEDYUR9QnPBNLZbd9x2nDaIKaIuSRtvlS9BjlMuxJKqN99C8O0txi/RP5/tvZ0=,iv:lJMHGEpMQgN4NyHBRnuIzHmTWIP76qYXFYHDQsqHcWU=,tag:3gSPe7QzBOaGBoQFrnHN6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
