---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
  interval: 1h
  values:
    server:
      retentionPeriod: 30d
      persistentVolume:
        enabled: true
        existingClaim: victoria-logs
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi
    vector:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true
