---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-single
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.13.1@sha256:2378116c1a212d76eca53b5ef9c4c1152c4d5f8fd0b41f840ab04164399bb66c
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
