apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:NjH2ZTmZge6x6zFgKcvC7t6+yon0r37u8+leuNI/yPmYoRKAC5meRYMAPqo=,iv:FylA3CzfsUBExy7Eihrys/IJX4QDK4Pi6Prjbp6FEEM=,tag:szfEsYmYYiQkdVCM0XvnJA==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:io3e9Nk=,iv:2i78Pu2t1T0YeGj5GBY+xGYG0uPa24qgHmW4/4CINBo=,tag:eh8pPPixqevYpGZObhdzyA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:3K9zXR2/EYVvAh5emBXsCw==,iv:hKJvWgLX9Mcg/ssMlKnAv/65oVztX8cO5011FHguLyA=,tag:5U5M24DXW8WJ7gZdgNKavQ==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:txSnm6Svs8Xywu4iqr718IMe6ilqceWxzxuOvfq4cuBD7aBpakvEDXgYH4w1gX16FnliGdJja9taToiZM+4y1FbjnUM+27Q9+uaFu3z7bSw6hnXBwSucLxrBEw8/znY40DcrwvYZQlBH5i27NPYVZBZqWG58Y98uND1LvwpnbJS7bcbXAywMww6uAX9JC+PzJjN3PlKak9+EflmwZcMTlDQt0ixgWfr6ztG0lWFhR/qsheK50VEREJAxmeogrm0WOlKM8D7dvpAnaUHS3YrQCVsLy5qV9Q9enBIaPX1qM48zknYU+bNYLshlUNsTHgXerwTFcYLmVbsXR+ZoXNNDm2T1Sj3i9uZRnTzIw/AZi8kp1n9jQFWPtP0njsunBVXuHcroDfrvxmX4e4Hlld/2A63TSedhm8SSIKCJjnOxcn6A5w3cCVLXkTx3Q8pxJsFdle5ndOyQV1TOkI1BsMNwBSrqyMurpspR0btGcrgxWVXlYtV9tIyIM7AbjrKG/+K11PPYB27VeowLnbtlxZmdWNipU11kvnCdajjRmjsOIw0dAdZhI/JeqhRD0hLM34LMKcHYtV+MU4K1YEn1tOt8OtznqcfCoiisdSJ74mhdtNowyxkDitoW0fcfJWuft0Uk7SsbvdwLwkJHMHTG10w=,iv:iRWQRVrfFNiF4HJPxo2m1YdhGQ/lGKU0DTz7jmmIxFk=,tag:sgFtdYpFR0yKFlG09UchHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WTFIWU5XYjI1SFE0bGVG
        dytuQU9uM2gzdmR4ZndzRDhIRVBRYzJRT204CnFVS1R6dEIrQ3JqbjRObzU3eXJq
        ZHBWdGVjTVpkeHkrTlRvRFBJTDdKMGcKLS0tIElFVlc0NGtDWWxObDJseUhpQ0Fw
        YWxZYXJsT013bUY4cC9YYlFwM09KbjQKmoiqQFpPyku7MvLO8RJ4GVEFTOoktILG
        q1woOL+yQih8rf2vAkJpfHrRfGoY6QvT2g/wWegFshHRhaDvmENpcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T16:21:20Z"
  mac: ENC[AES256_GCM,data:/acTMV1CpLUgPEPAOdVzOh8YiZUZj+9gJr029cHWsIv5UtzTgYOxFFsfPBGRAYSc/Y1NW92DNnuXnov5ASwSdyN+4Zxb0RJXKDhLUk4FWxvJRCQfmhAc5Aqwo3/gL0GwiUDzWx7O9Fi/oikav+pViVxabaMOQhKhGWUnaN7w188=,iv:hhsE+uDh+sxu8TTlYBdWGRisir7RC50v+q5vcUqD9w8=,tag:p9uEj7rJg25v97lkNd4OiQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
