---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openproject
spec:
  interval: 1h
  url: oci://ghcr.io/opf/helm-charts/openproject
  ref:
    tag: "13.13.1"
    digest: sha256:101bb3710110602dbdefe4b60096aae66307190228345ff091f8a371adf1d7bf
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openproject-valkey
spec:
  interval: 1h
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: "5.2.1"
    digest: sha256:f32d40ce76b5378acc96783424e3c5b7ec0274240484968a868b2256983514c3
