apiVersion: v1
kind: Secret
metadata:
  name: openproject-secret
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:uzrnBQCybu9flFAjvFNZgnDTClG7cBrB8AWffBVAwKrPD+9psi/jAhfIHtythZqtvO5s6tVrF4v/E7399ycNWQ4Av0CtlrbWJSwuc5SI73Iab0zS8B6bTNJpyr+9SSIf+MtbR4UB/4YEY+Gu2FDKrYHceZnB7vAyXryHmTVuzXc=,iv:lBiRjB7UZcqtwFvbtqpPJADu3gxB5gDX3ULPGU5Zdno=,tag:D87YmbvLSXXF7mvurh3ggQ==,type:str]
  HOCUSPOCUS_SECRET: ENC[AES256_GCM,data:3yQ+qjfsvCsImAYFvB2tf+8SzINZgrVKPzSQH255EQgvibsRii8GDKBxgQvWBRUoZ4LC3V2kFpAkDd+vaOuoVw==,iv:7ELqMieuWP46ws8XrWwSL5imWicdrs8l0iD15rXvvbk=,tag:6PbNmK+x8xU+wFjphNLbGg==,type:str]
  OPENPROJECT_SEED_ADMIN_USER_MAIL: ENC[AES256_GCM,data:/l2DLgS430+n1ydKg/OAoYCF/GOsMg==,iv:ulHVXV4V1eQku7mRLcEZdHV9691Fad0Dn0gWSj/mrP4=,tag:MzicZAGaF6I2oiOFpcYRTw==,type:str]
  OPENPROJECT_SEED_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:3AcNunnX1Y8C+1G24P6yHtc2JdmWIMPmcDsWHCbTGg==,iv:xnES5qjh5RNrcoCUDreA5a9bVJM+M0KA/0i/EwC4deU=,tag:VWQIhK+I4ddqSqE3O/GFEQ==,type:str]
  OPENPROJECT_SMTP__USER__NAME: ENC[AES256_GCM,data:UwNXkVw5v0qFzMf5x0gyw58mM2Y=,iv:0naEMyQZjaedddoZs/NWTA5q9RHmJpPBf63at07rmrQ=,tag:pq9/88XCiPGOwERrGAqMSg==,type:str]
  OPENPROJECT_SMTP__PASSWORD: ENC[AES256_GCM,data:Q4kb62eXPVc8brhHIY8vCqWMzuQ=,iv:siUgE8PZlXZPqxccqlXuqnPI2fAj6+mrKtL8e3S+7co=,tag:/Tkg7d871AQiHBVqrPBVOA==,type:str]
  OPENPROJECT_SMTP__ADDRESS: ENC[AES256_GCM,data:jL/+jUk6Vop1UrxxNKrDpVCw,iv:RGxmEqg8Ti5ozLtTxk44j1EC8UQKegNZRWxVDVnvZxI=,tag:fO757I4TWj+RahoxdbNkww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtREdOcENmaVVveGdHK01S
        eG9ZQ00vbmNUSEJIZU1GWFZCeDdNYUhXdVVjCmM3RzFpS2VsVERpOUR1K2wrUEpx
        OThDTVZwYWg3MGhSRmpDaDUxenJaY0UKLS0tIEVwQ3F4YWpWOFBySmhwbnZKZTh1
        UmZJOFptZFpJTHZGR0REcWZrdTJBancKwzVSNt6/jLT9nKFo9543ivNG5fgdzN9Q
        D9/C6GE6X+tMGM85qhWrl1A20BE+yGF0XjNKfOpm8CtxuNpwZV2fCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T11:42:55Z"
  mac: ENC[AES256_GCM,data:mauPxNbihX1eCEyc60tAs1PzH/ZAUyecEzbE6bSrAe4gDnfWjQNYe+ATDDZb4x5cB+N37mNOXk/7EPLN/HvXUjtuMzTDzhlgkXjWW4OKTkz9aEPmQfo94caOB0uOMD9/bWzvaU5Eni1g4wgkJBMbpbHzFcl7zTl33ap8B4HT0Tc=,iv:hPRkw4ySSy83R/9J8O7DHg/b7i7GCRos62zvXeaEjMc=,tag:9OdAFaSybHnPBmzLTnHVSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
