---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: samba-operator
    control-plane: controller-manager
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: samba-operator-system
