apiVersion: v1
kind: Secret
metadata:
  name: pingvin-share-oidc
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:5Kgm2xJS3Us9vev6xGGmv7BssVo4I4xou4n5gthr1T+J0pAujfU55w==,iv:kMlEks9YFMEoDoQRuSrq3jC/KvEPt2IhU9WzvMpd0ZU=,tag:4HJchXdjHBtQpNjyNOiHRA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MeYnTLnzFXZPiNNqRmYDzw489wiFEj/7g8jM0WFEHNpYp5eBInF+bDbCbJr7TE+l47kS13wgA89nd8xZtDQ0sFGlqB2c0ij6G4j2pMX3Fkw4rsVRkK9wNLztQpP8QP/GsGmYcwVXNGcVbfHQ3R30PHwzuuJ1gWvzfGgx+px+6Ng=,iv:QuyG6xpzIh+GDv3P++5D9CobdtfaLI6FfFx9frrd890=,tag:aMIblFfInB3Nps4Ime33yA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydXV2L0NuYkNUTTYvVC9Z
        ZlNuWUJxWmRWa00rbDRBVkcrOXhpOVEyaFhnCmpDbC81ZHJRZi9SbkU1NUFGOFRw
        T1hZS3hJRzB1aTlIYTc3WVV1SjRXT1kKLS0tIHZ3Z2VBT1RyZUpjVG9tNU5LTDZj
        a21PbzNrdGp4MkprWWRXZldlSXltV2cKzAcRG3joxYzp4hGszk3sXx9wmNfqtCj0
        GCj4FMqlbrZlHpChPvHul1owRuzrB9q5JED0oNQTStgEp7rDpQQV7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mqj2kqedv27ec0qe9wtwucv4qtgrlyjcj8u0pznmffmzxswsscus3q4tfj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T17:39:17Z"
  mac: ENC[AES256_GCM,data:IuJPRaoTTqunhOBFhIO0T8j3wl3RYw3mdluAhIVp98bNqCUI2nVQ1EccBhuH2EObgez5ajleDEt+U3zOegJfDbPxTqHt3VUUYcHFOPGaLKhh6k/EQWplYNxjOn1lxGBr30gYPjEJLyovwZm1Vjn5fbaMeIv/28/yBitaFbz4QHA=,iv:IvzdtrAokdkh503AKiNR1sBDb1IA/sgyak9mtlHaIMw=,tag:vpamfsdKaOKS0M8XzomOlA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
