---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-birdnet-go-bucket
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/birdnet-go/bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/bucket
  postBuild:
    substitute:
      BUCKET: birdnet-go
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-birdnet-go-migration
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/birdnet-go/migration
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: birdnet-go
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-birdnet-go
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/birdnet-go/app
  prune: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: automation-birdnet-go-bucket
  postBuild:
    substitute:
      APP: birdnet-go
      BUCKET: birdnet-go
      VOLSYNC_CAPACITY: 50Gi
